name: Message Notify
on: [push]
jobs:

  notification:
    runs-on: ubuntu-latest
    steps:
    - name: feishu text message
      uses: foxundermoon/feishu-action@v2
      with:
        url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
        msg_type: text
        content: |
          text: |
            repository: ${{ github.repository }}
            branch : ${{ github.ref_name }}
            committer: ${{ github.actor }}
            compare: ${{ github.event.compare }}
            job status: ${{ job.status }}
            website: https://seashop.github.io/yummy-h5/
